matrix:
  include:
    - language: python
      sudo: required
      dist: trusty

      python: 3.5

      install:
        - pip3 install codecov pytest pytest-cov
        - ./utils/jumspcale_install.sh
        - ./utils/zrobot_install.sh

      script:
        - make test

      after_success:
        - codecov

    - language: python
      sudo: true
      dist: trusty
      if: type IN (api, cron)

      python: 3.5

      install:
        - curl -s https://install.zerotier.com/ | sudo bash
        - ./utils/jumspcale_install.sh ${js9_branch}
        - ./utils/zrobot_install.sh ${zrobot_branch}

      before_script:
        - cd ./tests/integration_tests; bash travis.sh setup

      script:
        - bash travis.sh run
